### ISSUE TITLE
Receive in protocol/rep can give duplicate messages

### ISSUE THREAD

**Issue by weberr13** [go-mangos/mangos#298]
In our testing I have come up with an issue that Rep sockets can successfully receive the same message twice in some (but not all) cases.  It appears to be a data race but it has made the sockets difficult to impossible to use without implementing deduplication logic in our code. 
This error is spirattic and appears to evade the go race detector but I have a simple test that reproduces it:

```
package fiddler

import (
	"bytes"
	"fmt"

	"testing"

	REP "github.com/go-mangos/mangos/protocol/rep"
	REQ "github.com/go-mangos/mangos/protocol/req"
	INPROC "github.com/go-mangos/mangos/transport/inproc"
	IPC "github.com/go-mangos/mangos/transport/ipc"
	TCP "github.com/go-mangos/mangos/transport/tcp"
	TLSTCP "github.com/go-mangos/mangos/transport/tlstcp"
)

func TestRaceInSockets(t *testing.T) {

	msgCount := 5
	URL := "inproc://RaceInSockets-test"
	d, err := REQ.NewSocket()
	if err != nil {
		t.Fatal(err)
	}
	d.AddTransport(INPROC.NewTransport())
	d.AddTransport(IPC.NewTransport())
	d.AddTransport(TCP.NewTransport())
	d.AddTransport(TLSTCP.NewTransport())
	err = d.Dial(URL)
	if err != nil {
		t.Fatal(err)
	}
	f, err := REP.NewSocket()
	if err != nil {
		t.Fatal(err)
	}
	f.AddTransport(INPROC.NewTransport())
	f.AddTransport(IPC.NewTransport())
	f.AddTransport(TCP.NewTransport())
	f.AddTransport(TLSTCP.NewTransport())
	err = f.Listen(URL)
	if err != nil {
		t.Fatal(err)
	}
	failure := make(chan error, 10)
	go func() {
		lastGot := []byte{}
		for i := 1; i <= msgCount; i++ {
			rmsg, recvError := f.Recv()
			if recvError != nil {
				failure <- recvError
			}

			if bytes.Equal(lastGot, rmsg) {
				failure <- fmt.Errorf("Got duplicate receive")
			}
			lastGot = rmsg
			f.Send(rmsg)
		}
	}()

	for i := 1; i <= msgCount; i++ {
		uniqMsg := []byte(fmt.Sprintf("%v", i))
		err = d.Send(uniqMsg)
		if err != nil {
			t.Fatal(err)
		}
		reply, err := d.Recv()
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(uniqMsg, reply) {
			t.Fatal(err)
		}
		select {
		case err = <-failure:
			t.Fatal(err)
		default:
			break
		}
	}

}
```

the above will reliably find a duplicate message on Recv() (ps using go 1.8 linux/amd64)

**Comment by gdamore** [comment]
Thanks for the test case.  I agree that this is a bad bug, and needs to be
fixed asap.

**Comment by grrtrr** [comment]
I tested b87c068bc8eaa0062307e36fca054353f4bbda91 for about close 2 hours, using the above test script.
In about 66 out of 7385 runs (0.89%) it still fails with `Got duplicate receive`.

**Comment by gdamore** [comment]
Ok. The thats not great news but less than 1% dup rate is not the end of
the world. I think this may just be due to scheduling. I will think about
better ways to get this going forward.

**Comment by gdamore** [comment]
Looking at this more closely, I think the problem is that a race can occur when first setting up the connection.  Because the sender does not wait for the connection to before sending, it can actually enqueue a message at almost the exact same time that the endpoint is added, leading to the duplicate message.  This is really an edge case.  Adding a short delay after the connection is established before sending the message will eliminate that -- this is a standard problem with SP protocols -- they are designed to always be connected; if you disconnect too soon after, the message is lost.  Now, with this change, if you don't wait for the connection to establish before sending the message, you can wind up having threads race to deliver this.

One thing that I can do to reduce is to try to ensure that we "clear" the condition no matter what, when the sender is entered -- and also when moving forward from the resender.  That should largely eliminate even these small percentage of duplicates.

**Comment by grrtrr** [comment]
Thank you for looking into this. I personally find that both the code and scenarios become increasingly more complex to reason about and cater for.
The original design was elegant and robust and in months of use has not given us any trouble, giving much confidence in the code before dc23bead70e59c9e41097971694465490301c422.

I found the addition of the wakeq difficult to understand - as far as I could see it was only to make it "fail faster" when an endpoint disappears.

Anyway, after reverting the changes specific to `protocol/req/req.go` in dc23bead70e59c9e41097971694465490301c422 I still get 1 duplicate receive in `TestRaceInSockets`, after 18330 runs (~0.0054%).

**Comment by gdamore** [comment]
I understand your concerns about complexity & simplicity -- remember I was the person who created mangos in the first place.  Unfortunately, as I've spent a lot more time with these protocols (in the nanomsg and nng code bases) I've discovered that the simple design was a bit naive and *too simple*.

If you have reliable networking, you should never see the fail fast flow, and that complexity should be idle.  The fact that we're seeing it now means that something else is wrong in our understanding.

I suppose if this really bothers you I could make this functionality something that can be disabled via a tunable.  I'm not a fan of that -- yet more complexity.

Instead I want to work to understand the duplicates (actually I think I *do* but I need to do some experiments to verify my hypothesis first) and fix it "properly".

The closed-channel problem is something I've not seen before -- and I don't think is related to this code at all -- its in the REP code not the REQ code, at any rate.  So let's please not conflate the issue (even though I was guilty of doing that at first.)

**Comment by gdamore** [comment]
I have a change that reduces the incident rate to about 0.3%.  Having said that, I'm pretty sure that if I were to just add a short sleep after the connection before sending the request, that this would vanish entirely.

I'm seriously reconsidering my earlier position.  I'm not sure that the fix isn't worse than the problem itself.  The old code behaved "correctly", generally.  (I am willing to chalk that one duplicate receive up to a problem in the scheduler.)

The real problem is that the use of channels here creates several additional layers of asynchronicity that we would best be without.  (Those actually hurt both the simplicity and the performance.)  I'll need to think about this in the long term -- it may be time refactor the core gradually to make better use of more standard synchronization primitives.

**Comment by grrtrr** [comment]
Thank you so much for looking into this. I am lacking the exposure to the intricacies of the protocols; but would be more than happy to test new things.
I was very happy with the original flow; and yes orchestrating multiples of go channels is complex.

These scalability protocols are very valuable in the cloud context (reliable networking, unreliable/volatile instances). Perhaps the situation is similar to TCP,
which originally was simple, but then had tons of additions for every conceivable networking type.

**Comment by gdamore** [comment]
Ok, I'm going to make a decision.  I'll roll back the portion of the 298 fix that complicated req.  My attempt to "fix" this needs more work, and ultimately I'm convinced that I need to go back and redesign this to stop using channels.  Locks and condvars are less painful in the long run, and will be better (particularly since I can then just use a couple of boolean flags).

**Comment by grrtrr** [comment]
Thank you sir. I was not able to comment, just noticed the behaviour. If it is just flags, perhaps it could be done with [sync/atomic](https://golang.org/pkg/sync/atomic/).

**Comment by weberr13** [comment]
Thank you for looking into this.  For some background info, that test case was derived from real world code we have running on AWS.  Basically we used nanomsg Req/Rep to communicate over TCP and then dump those responses into a channel.  The duplicates gradually filled the channel since the receiving end would not know when and if to drain "extra" client responses once it had the initial reply that it needed.  Eventually (over 100,000's of requests a day) the application would time out and require the system to be restarted.  If the fixes currently committed will at least reduce the likelihood of these duplicates it will help us immensely.  With all the reverts can you tell me @gdamore if I should expect that the latest will reduce how often this occurs or should I continue to wait?

**Comment by grrtrr** [comment]
I have been running tests on  e5e6478f44cda1eb8427b590755270e2704a990d for a couple days now: 
![image](https://user-images.githubusercontent.com/5132989/34448331-7fe85e78-eca9-11e7-99e0-0590552cb9cf.png)

_424,102 runs without a single duplicate_ (!) (the test below just tests the rep race condition which was fixed).

**Comment by weberr13** [comment]
Wow, that is helpful @grrtrr , I will vendor this into our project now.

**Comment by gdamore** [comment]
Yes, you should go ahead and update to the latest.
